-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 03:15:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema basededatos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `basededatos` ;

-- -----------------------------------------------------
-- Schema basededatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basededatos` DEFAULT CHARACTER SET utf8 ;
USE `basededatos` ;

-- -----------------------------------------------------
-- Table `basededatos`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`usuario` (
  `Id_Usuario` INT NOT NULL,
  `rol` INT NOT NULL,
  `tipo_identificación` VARCHAR(45) NOT NULL,
  `primer_nombre` VARCHAR(25) NOT NULL,
  `segundo_nombre` VARCHAR(25) NULL DEFAULT NULL,
  `primer_apellido` VARCHAR(25) NOT NULL,
  `segundo_apellido` VARCHAR(25) NULL DEFAULT NULL,
  `direccion` VARCHAR(85) NOT NULL,
  `email` VARCHAR(75) NULL DEFAULT NULL,
  `telefono` INT NOT NULL,
  `contraseña` VARCHAR(15) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  CONSTRAINT `fk_Usuario_ROL1`
    FOREIGN KEY (`rol`)
    REFERENCES `basededatos`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Usuario_ROL1_idx` ON `basededatos`.`usuario` (`rol` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`administrador` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Administrador_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Administrador_Usuario1_idx` ON `basededatos`.`administrador` (`id` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`aux_cocina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`aux_cocina` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_auxCocina_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_auxCocina_Usuario1_idx` ON `basededatos`.`aux_cocina` (`id` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`cajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cajero` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cajero_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cajero_Usuario1_idx` ON `basededatos`.`cajero` (`id` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cliente` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cliente_Usuario1_idx` ON `basededatos`.`cliente` (`id` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`pedido` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  `valor_unitario` DOUBLE NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `tipo_pedido` VARCHAR(45) NOT NULL,
  `telefono` INT(11) NULL,
  `punto_entrega` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(95) NULL DEFAULT NULL,
  `Estado` INT NOT NULL,
  PRIMARY KEY (`Id`),
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Pedidos_Cliente1_idx` ON `basededatos`.`pedido` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`factura` (
  `id` INT NOT NULL,
  `pedidos` INT NOT NULL,
  `cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `precio_Unitario` DOUBLE NOT NULL,
  `Iva` INT NOT NULL,
  `precio_total` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Factura_Pedidos1`
    FOREIGN KEY (`pedidos`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Factura_Pedidos1_idx` ON `basededatos`.`factura` (`pedidos` ASC);

CREATE INDEX `fk_factura_cliente1_idx` ON `basededatos`.`factura` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`cajero_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`cajero_has_factura` (
  `Factura` INT NOT NULL,
  `Cajero` INT NOT NULL,
  PRIMARY KEY (`Factura`, `Cajero`),
  CONSTRAINT `fk_Cajero_has_Factura_Cajero1`
    FOREIGN KEY (`Cajero`)
    REFERENCES `basededatos`.`cajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cajero_has_Factura_Factura1`
    FOREIGN KEY (`Factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Cajero_has_Factura_Factura1_idx` ON `basededatos`.`cajero_has_factura` (`Factura` ASC);

CREATE INDEX `fk_Cajero_has_Factura_Cajero1_idx` ON `basededatos`.`cajero_has_factura` (`Cajero` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`operario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`operario` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Operario_Usuario1`
    FOREIGN KEY (`id`)
    REFERENCES `basededatos`.`usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Operario_Usuario1_idx` ON `basededatos`.`operario` (`id` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`despacho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`despacho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedidos` INT NOT NULL,
  `cliente` INT NOT NULL,
  `operario` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(120) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `punto_entrega` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Despacho_Pedidos1`
    FOREIGN KEY (`pedidos`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_operario1`
    FOREIGN KEY (`operario`)
    REFERENCES `basededatos`.`operario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_despacho_cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Despacho_Pedidos1_idx` ON `basededatos`.`despacho` (`pedidos` ASC);

CREATE INDEX `fk_despacho_operario1_idx` ON `basededatos`.`despacho` (`operario` ASC);

CREATE INDEX `fk_despacho_cliente1_idx` ON `basededatos`.`despacho` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`tipo_insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`tipo_insumo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`insumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_insumo` INT NOT NULL,
  `auxCocina` INT NOT NULL,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(65) NULL DEFAULT NULL,
  `cantidad` DOUBLE NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Insumos_auxCocina1`
    FOREIGN KEY (`auxCocina`)
    REFERENCES `basededatos`.`aux_cocina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_tipo_insumo1`
    FOREIGN KEY (`tipo_insumo`)
    REFERENCES `basededatos`.`tipo_insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_tipo_insumo1_idx` ON `basededatos`.`insumo` (`tipo_insumo` ASC);

CREATE INDEX `fk_Insumos_auxCocina1_idx` ON `basededatos`.`insumo` (`auxCocina` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_producto` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DOUBLE NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `imagenP` LONGBLOB NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`insumo_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumo_has_producto` (
  `insumo` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`insumo`, `producto`),
  CONSTRAINT `fk_Insumos_has_Productos_Insumos1`
    FOREIGN KEY (`insumo`)
    REFERENCES `basededatos`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_has_Productos_Productos1`
    FOREIGN KEY (`producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_has_Productos_Productos1_idx` ON `basededatos`.`insumo_has_producto` (`producto` ASC);

CREATE INDEX `fk_Insumos_has_Productos_Insumos1_idx` ON `basededatos`.`insumo_has_producto` (`insumo` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`proovedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo_documento` VARCHAR(10) NOT NULL,
  `documento` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`insumo_has_proovedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`insumo_has_proovedor` (
  `insumo` INT NOT NULL,
  `proveedor` INT NOT NULL,
  PRIMARY KEY (`insumo`, `proveedor`),
  CONSTRAINT `fk_Insumos_has_Proovedores_Insumos1`
    FOREIGN KEY (`insumo`)
    REFERENCES `basededatos`.`insumo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Insumos_has_Proovedores_Proovedores1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `basededatos`.`proovedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Insumos_has_Proovedores_Proovedores1_idx` ON `basededatos`.`insumo_has_proovedor` (`proveedor` ASC);

CREATE INDEX `fk_Insumos_has_Proovedores_Insumos1_idx` ON `basededatos`.`insumo_has_proovedor` (`insumo` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`metodo_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`metodo_de_pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`metodo_de_pago_has_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`metodo_de_pago_has_factura` (
  `metodoDePago` INT NOT NULL,
  `factura` INT NOT NULL,
  PRIMARY KEY (`metodoDePago`, `factura`),
  CONSTRAINT `fk_Metodo de Pago_has_Factura_Factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Metodo de Pago_has_Factura_Metodo de Pago1`
    FOREIGN KEY (`metodoDePago`)
    REFERENCES `basededatos`.`metodo_de_pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Metodo de Pago_has_Factura_Factura1_idx` ON `basededatos`.`metodo_de_pago_has_factura` (`factura` ASC);

CREATE INDEX `fk_Metodo de Pago_has_Factura_Metodo de Pago1_idx` ON `basededatos`.`metodo_de_pago_has_factura` (`metodoDePago` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`tipopqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`tipopqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `basededatos`.`pqrs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`pqrs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `tipoPQRS` INT NOT NULL,
  `administrador` INT NOT NULL,
  `cliente` INT NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_PQRS_Administrador1`
    FOREIGN KEY (`administrador`)
    REFERENCES `basededatos`.`administrador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `basededatos`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PQRS_tipoPQRS1`
    FOREIGN KEY (`tipoPQRS`)
    REFERENCES `basededatos`.`tipopqrs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_PQRS_tipoPQRS1_idx` ON `basededatos`.`pqrs` (`tipoPQRS` ASC);

CREATE INDEX `fk_PQRS_Administrador1_idx` ON `basededatos`.`pqrs` (`administrador` ASC);

CREATE INDEX `fk_PQRS_Cliente1_idx` ON `basededatos`.`pqrs` (`cliente` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`producto_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`producto_has_pedido` (
  `Pedido` INT NOT NULL,
  `Producto` INT NOT NULL,
  PRIMARY KEY (`Pedido`, `Producto`),
  CONSTRAINT `fk_Productos_has_Pedidos_Pedidos1`
    FOREIGN KEY (`Pedido`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_has_Pedidos_Productos1`
    FOREIGN KEY (`Producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_Productos_has_Pedidos_Pedidos1_idx` ON `basededatos`.`producto_has_pedido` (`Pedido` ASC);

CREATE INDEX `fk_Productos_has_Pedidos_Productos1_idx` ON `basededatos`.`producto_has_pedido` (`Producto` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`pedido_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`pedido_has_producto` (
  `pedido` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`pedido`, `producto`),
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`pedido`)
    REFERENCES `basededatos`.`pedido` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_pedidos_has_productos_productos1_idx` ON `basededatos`.`pedido_has_producto` (`producto` ASC);

CREATE INDEX `fk_pedidos_has_productos_pedidos1_idx` ON `basededatos`.`pedido_has_producto` (`pedido` ASC);


-- -----------------------------------------------------
-- Table `basededatos`.`factura_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basededatos`.`factura_has_producto` (
  `factura` INT NOT NULL,
  `producto` INT NOT NULL,
  PRIMARY KEY (`factura`, `producto`),
  CONSTRAINT `fk_factura_has_producto_factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `basededatos`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_has_producto_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `basededatos`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_factura_has_producto_producto1_idx` ON `basededatos`.`factura_has_producto` (`producto` ASC);

CREATE INDEX `fk_factura_has_producto_factura1_idx` ON `basededatos`.`factura_has_producto` (`factura` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
